version: '3.8'

services:
  rwallet-online:
    build: .
    container_name: rwallet-online
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.rwallet.rule=Host(`rwallet.online`) || Host(`www.rwallet.online`) || Host(`wallets.bondingcurve.tech`)"
      - "traefik.http.routers.rwallet.entrypoints=web"
      - "traefik.http.services.rwallet.loadbalancer.server.port=80"
    networks:
      - traefik-public

networks:
  traefik-public:
    external: true
